
all:
	make -C test_fs
	make -C test_time
	make -C test_freerun_timer
	make -C test_spidev
	make -C test_ipcufs
	make -C test_fb
clean:
	make clean -C test_fs
	make clean -C test_time
	make clean -C test_freerun_timer
	make clean -C test_spidev
	make clean -C test_ipcufs
	make clean -C test_fb

