#
# Configuration for Warp!! helper
#

# warpd IPC key file path
WARP_IPC_KEY="/tmp/warpd_add"

# warpd IPX key ID (warpd rx)
WARP_DAEMON_ID="W"

# warpd IPX key ID (warpd tx)
WARP_CLIENT_ID="w"

# number of process to wait for snapshot script execution
WARP_PROCESSES=1

# messgae notification interval(usec) of each process
WARP_INTERPROCESS_DELAY=100

# full path of snapshot/snapshot_wrapper script
WARP_SNAPSHOT_SCRIPT="/tmp/snapshot_wrapper_nf_1"


#
# debug
#

# dump debug messages
#WARP_HELPER_DEBUG=1

# emulate the warp snapshot acquisition
#WARP_EMULATION_FLAG=1

# dump the process queuing table
#WARP_WAITING_TABLE=1
