IP=192.168.137.16
GATEWAY=192.168.137.1
ETHER_TYPE=usb3
ENABLE_RTSP=0
DYNAMIC_IP=0
HTTP_PORT=8080
RAM_DCIM=/run/SD/mmcblk0p1/DCIM
GPS_BAUDRATE=115200
GPS_OFFSET=100
GPS_PROTOCOL=mavlink
LOG_LEVEL=1
LOG_FILE=/media/SD/log.txt
NO_APPS=0
