#@TYPE: Machine
#@NAME: sc2000-eb
#@DESCRIPTION: Machine configuration for Socionext mlb01

DEFAULTTUNE = "cortexa7t"
include conf/machine/include/tune-cortexa7.inc

TARGET_FPU=""
TUNE_FEATURES="arm armv7a thumb cortexa7t"
PACKAGE_EXTRA_ARCHS_tune-cortexa7 = "${PACKAGE_EXTRA_ARCHS_tune-armv7a} cortexa7"
PACKAGE_ARCHS+=" cortexa7t2 cortexa7"

IMAGE_FSTYPES += "tar.bz2 ubi"
EXTRA_IMAGECMD_jffs2 = "-lnp "
MKUBIFS_ARGS = " -m 2048 -e 126976 -c 3600 "
UBINIZE_ARGS = " -p 16KiB -m 2048 -s 2048 "

SERIAL_CONSOLE = "115200 ttyUSI0"

#PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto"
#PREFERRED_VERSION_linux-yocto ?= "3.14%"
PREFERRED_PROVIDER_libjpeg-native = "libjpeg-turbo-native"
PREFERRED_PROVIDER_libjpeg = "libjpeg-turbo"

IMAGE_INSTALL_append += " \
	  mtd-utils \
	  mtd-utils-ubifs \
	  connman \
	  connman-client \
	  connman-tools \
	  exfat-utils \
	  dosfstools \
	  gstreamer1.0-meta-base \
	  gstreamer1.0-rtsp-server \
	  gstreamer1.0-plugins-base \
	  gstreamer1.0-plugins-good \
	  gstreamer1.0-plugins-bad \
	  gstreamer1.0-plugins-good-video4linux2 \
	  gstreamer1.0-plugins-good-rtpmanager \
	  gstreamer1.0-plugins-good-rtp \
	  gstreamer1.0-plugins-good-udp \
	  gstreamer1.0 \
	  boost \
	  hostapd \
	  snisysinit \
	  ipcu \
	  input-handler \
	  hid \
	  warphelper \
	  drvtest \
	  sniusbtest \
	  sninettest \
	  sniuvctest \
	  sniutil \
	  ispterm \
	  usbhostcomp \
	  iw \
	  iperf \
	  jo \
	  jq \
	  httpsetting \
	  bootchart \
	  i2c-tools \
	  glog \
	  mtpserver \
	  gstipcusrc \
	  wpa-supplicant \
	  gstrtsp \
	  capaInfo \
	  capasample \
	  chkappfile \
	  sniwifi \
          openssh \
          iperf3 \
          util-linux \
	  unfs3 \
	  rpcbind \
	  portmap \
	"


IMAGE_INSTALL_remove = " ofono bluez5 bluez-hcidump bluez4"

DISTRO_NAME = "Socionext sc2000 EVB rootfs"

DISTRO_FEATURES_remove = "3g"
DISTRO_FEATURES_append = " wifi systemd "

PACKAGECONFIG_append_pn-packagegroup-core-standalone-sdk-target = \
	" gstreamer1.0-dev \
	  gstreamer1.0-plugins-base-dev \
	  gstreamer1.0-plugins-good-dev \
	"

VIRTUAL-RUNTIME_init_manager = "systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"
VIRTUAL-RUNTIME_initscripts = ""

#PACKAGECONFIG_append_pn-directfb = " drmkms"

KERNELDEPMODDEPEND = ""
USE_DEPMOD = "0"

MACHINE_FEATURES = "usbgadget usbhost vfat alsa"
