#@TYPE: Machine
#@NAME: sc2000-eb
#@DESCRIPTION: Machine configuration for Socionext mlb01

DEFAULTTUNE = "cortexa7t"
include conf/machine/include/tune-cortexa7.inc

TARGET_FPU=""
TUNE_FEATURES="arm armv7a thumb cortexa7t"
PACKAGE_EXTRA_ARCHS_tune-cortexa7 = "${PACKAGE_EXTRA_ARCHS_tune-armv7a} cortexa7"
PACKAGE_ARCHS+=" cortexa7t2 cortexa7"

IMAGE_FSTYPES += "tar.bz2 ubi"
EXTRA_IMAGECMD_jffs2 = "-lnp "
MKUBIFS_ARGS = " -m 2048 -e 126976 -c 3600 "
UBINIZE_ARGS = " -p 16KiB -m 2048 -s 2048 "

SERIAL_CONSOLE = "115200 ttyUSI0"

PREFERRED_PROVIDER_virtual/kernel ?= "linux-yocto"
PREFERRED_VERSION_linux-yocto ?= "3.14%"
PREFERRED_PROVIDER_libjpeg-native = "libjpeg-turbo-native"
PREFERRED_PROVIDER_libjpeg = "libjpeg-turbo"

IMAGE_INSTALL_append += \
	" connman \
	  connman-client \
	  connman-tools \
	  mtpserver \
	  ipcu \
	  snisysinit \
	  sniusbtest \
	  warphelper \
	  sniutil \
	  e2fsprogs \
	  ispterm \
	  sniuvctest \
	"

IMAGE_INSTALL_remove = " ofono bluez5 bluez-hcidump bluez4"

DISTRO_NAME = "Socionext sc2000 EVB tiny rootfs"

DISTRO_FEATURES_remove = "3g"
DISTRO_FEATURES_append = " wifi systemd "

#PACKAGECONFIG_append_pn-packagegroup-core-standalone-sdk-target = \
#	" directfb-dev \
#	  gstreamer1.0-dev \
#	  gstreamer1.0-plugins-base-dev \
#	  gstreamer1.0-plugins-good-dev \
#	"

VIRTUAL-RUNTIME_init_manager = "systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"
VIRTUAL-RUNTIME_initscripts = ""

#PACKAGECONFIG_append_pn-directfb = " drmkms"

KERNELDEPMODDEPEND = ""
USE_DEPMOD = "0"

MACHINE_FEATURES = "usbgadget usbhost vfat alsa"
