#H:/serverroot     # define the server root. It will override -h
#A:172.20.         # Allow address from 172.20.0.0/16
#A:10.0.0.0/25     # Allow any address from 10.0.0.0-10.0.0.127
#A:10.0.0.0/255.255.255.128  # Allow any address that previous set
#A:127.0.0.1       # Allow local loopback connections
#D:*               # Deny from other IP connections
#E404:/path/e404.html # /path/e404.html is the 404 (not found) error page
I:index.html      # Show index.html when a directory is requested

#P:/url:[http://]hostname[:port]/new/path
#                  # When /urlXXXXXX is requested, reverse proxy
#                  # it to http://hostname[:port]/new/pathXXXXXX

#/cgi-bin:foo:bar  # Require user foo, pwd bar on urls starting with /cgi-bin/
#/adm:admin:setup  # Require user admin, pwd setup on urls starting with /adm/
#/adm:toor:PaSsWd  # or user toor, pwd PaSsWd on urls starting with /adm/
#.au:audio/basic   # additional mime type for audio.au files
#*.php:/path/php   # run xxx.php through an interpreter
