start 192.168.2.10                                                              
end 192.168.2.20                                                                
max_leases 11                                                                
interface wlan0                                                                  
opt dns 192.168.2.1                                                        
opt subnet 255.255.255.0                                                        
opt router 192.168.2.1  
