/*
 *
 * This file is automatically generated. Do not change.
 * Generate time : 2022/12/29 11:47:00
 *
 */

#include <mptk_typedef.h>
EXPORT const UB system_conf [] = {
	"TSysPrNum	4\n"
	"TKerPrNum	2\n"
	"TMaxTskId	300\n"
	"TMaxSemId	300\n"
	"TMaxFlgId	500\n"
	"TMaxMbxId	50\n"
	"TMaxMtxId	200\n"
	"TMaxMbfId	100\n"
	"TMaxPorId	50\n"
	"TMaxMpfId	50\n"
	"TMaxMplId	20\n"
	"TMaxDomId	100\n"
	"TMaxCycId	80\n"
	"TMaxAlmId	40\n"
	"TMaxResId	60\n"
	"TMaxSsyId	50\n"
	"TMaxSsyPri	16\n"
	"TSysStkSz	16384\n"
	"TSVCLimit	3\n"
	"TOAPLimit	0\n"
	"TTimPeriod	1\n"
	"TMaxRegDev	32\n"
	"TMaxOpnDev	64\n"
	"TMaxReqDev	64\n"
	"TDEvtMbfSz	1024	64\n"
	"TEV_MsgEvt	1\n"
	"TEV_MsgBrk	2\n"
	"TEV_GDI	3\n"
	"TEV_FFLock	4\n"
	"TRealMemEnd	0xDFFFFFFF\n"
	"TSmpcallIpiIrq	1\n"
	"TSmpcallIpiLevel	0\n"
	"TAbtStkSz	64\n"
	"TUndStkSz	64\n"
	"TIrqStkSz	512\n"
	"TFiqStkSz	128\n"
	"TMaxExcpHdr	10\n"
	"TInitTskPri	250\n"
};
