require conf/distro/poky.conf


BUILD_VERSION ?= "unknown"
BUILD_DATE ?= "unknown"

IMAGE_INSTALL_append += "qt4-embedded libexif e2fsprogs ppp ffmpeg cppzmq-dev estone-overlay m10v-multimedia-server camera-server gpsd vue-frontend hdmi-ui ca7-rtos boost"
LICENSE_FLAGS_WHITELIST = "commercial"